### ISSUE TITLE
Lists should use just <li>

### ISSUE THREAD

**Issue by dlfivefifty** [mpastell/Weave.jl#162] opened 2018-12-11 13:55 UTC
At the moment a list like 

1. Item 1
2. Item 2

Generates the HTML `<li><p>` which puts too much spacing. Just `<li>` is much better.

**Comment by tlnagy** [comment] 2019-01-03 19:45
This seems to be caused by Base's markdown library (that Weave.jl uses internally) wrapping all list items inside of a paragraph.

```julia
julia> using Markdown

julia> c = Markdown.parse("""
       1. Test
       2. Test2
       """);

julia> c.content
1-element Array{Any,1}:
 Markdown.List(Any[Any[Paragraph(Any["Test"])], Any[Paragraph(Any["Test2"])]], 1, false)
```

We could change it to ignore the outer paragraph wrapping inside lists like `Markdown` appears to do in `println`, but doesn't do in `display`:

```
julia> println(c)
1. Test
2. Test2


julia> display(c)
    1.   Test

    2.   Test2

```

Thoughts @mpastell?

**Comment by mpastell** [comment] 2019-01-04 09:00
The simplest fix would probably be to change the CSS to fix the spacing issue. There is no simple fix for this issue in the current markdown writer.

**Closed** 2019-02-28 08:50 UTC
